worker_processes auto;

events {
    worker_connections 4096;
}

http {
    include      mime.types;
    default_type application/octet-stream;

    sendfile on;

    keepalive_timeout 65;

    server {
        listen      1443 ssl;
        server_name localhost;

        access_log /opt/nginx-1.28.0/logs/lnxctl.access.log;
        error_log  /opt/nginx-1.28.0/logs/lnxctl.error.log;

        ssl_certificate     /opt/nginx-1.28.0/ssl/example.com.crt;
        ssl_certificate_key /opt/nginx-1.28.0/ssl/example.com.key;

        client_max_body_size 0;

        location / {
            proxy_pass http://127.0.0.1:1234;

            proxy_pass_header Server;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_buffering off;
            proxy_request_buffering off;

            proxy_read_timeout 900;
            proxy_send_timeout 900;
        }

        location ~ ^/api/.*/ws_ {
            proxy_pass http://127.0.0.1:1234;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;
        }
    }
}
